# This is a basic workflow to help you get started with Actions
name: Deployment
run-name: Continuos Deployment to EKS - ${{ github.ref_name }}
# Controls when the workflow will run
on:
  push:
    branches:
      - actions

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Caching
        uses: actions/cache@v3
        id: my-cache
        with:
          path: my_new_file
          key: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: creating file
        run: |
          touch my_new_file
          echo "este es contenido del carchivo" > my_new_file

      - name: Checking cache
        if: steps.my-cache.outputs.cache-hit == 'true'
        run: cat my_new_file

  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: [build]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Caching
        uses: actions/cache@v3
        id: my-cache
        with:
          path: my_new_file
          key: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Checking cache
        if: steps.my-cache.outputs.cache-hit == 'true'
        run: echo NO hay cache

      # Runs a single command using the runners shell
      - name: Kubernete deploy
        run: echo kubectl apply .........

  test:
    runs-on: ubuntu-22.04
    needs: [deploy]
    steps:
      - name: testing
        run: echo "testing, testing ..."