# This is a basic workflow to help you get started with Actions
name: Deployment-reusable
# Controls when the workflow will run.
on:
  push:
    branches:
      - reusable

jobs:
  building:
    uses: CharlyMillan/.github/.github/workflows/reusable_workflow.yml@main